name: Test and push from develop
on:
  push:
  pull_request:
    branches: [ develop ]
    paths:
    - '**.cs'
    - '**.csproj'
env:
  DOTNET_VERSION: '8' # The .NET SDK version to use

jobs:
  test:
      name: build-and-test-${{matrix.os}}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]

      steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  push:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        working-directory: .
        run: docker build . -f ./OS.API/Dockerfile -t banteroni/opensupernova:develop
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image to Docker Hub
        run: docker push banteroni/opensupernova:develop